spring.application.name=agendamento
spring.datasource.url=jdbc:postgresql://localhost:5432/atletica_agendamento
spring.datasource.username=atletica_user
spring.datasource.password=atleticalouco
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
